CREATE TABLE users(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
password VARCHAR(100) NOT NULL CHECK(LENGTH(password)>=2 AND LENGTH(password)<=100),
last_updated_date DATE NOT NULL,
created_date DATE NOT NULL
);

